CREATE TABLE meituan_app_download (
    id BIGINT NOT NULL,
    android_link VARCHAR(100) NOT NULL,
    ios_link VARCHAR(100) NOT NULL DEFAULT '',
    remark VARCHAR(500),
    status SMALLINT NOT NULL DEFAULT 0,
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted SMALLINT  NOT NULL DEFAULT 0,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

